# Generated by Django 5.2.9 on 2025-12-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('link', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-date'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Shalini Chaturvedy', max_length=100)),
                ('title', models.CharField(default='Data Analyst | Cloud & ML Enthusiast', max_length=200)),
                ('email', models.EmailField(default='shalini.chaturvedy@example.com', max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(default='Bengaluru, Karnataka, India', max_length=200)),
                ('hero_subtitle', models.TextField(default='Transforming data into actionable insights')),
                ('typing_texts', models.TextField(default='Data Analyst,Cloud & ML Enthusiast,Python Developer', help_text='Comma-separated list of texts for typing effect')),
                ('about_text', models.TextField(blank=True)),
                ('profile_image', models.ImageField(blank=True, upload_to='profile/')),
                ('resume_file', models.FileField(blank=True, upload_to='documents/')),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('projects_count', models.PositiveIntegerField(default=0)),
                ('internships_count', models.PositiveIntegerField(default=0)),
                ('certifications_count', models.PositiveIntegerField(default=0)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('programming', 'Programming & Data'), ('cloud', 'Cloud & Systems'), ('visualization', 'Visualization'), ('other', 'Other')], max_length=50)),
                ('proficiency', models.PositiveIntegerField(default=80, help_text='Proficiency level 0-100')),
                ('icon_class', models.CharField(blank=True, help_text='Font Awesome or custom icon class', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'order', 'name'],
            },
        ),
    ]
